# Generated by Django 5.0.7 on 2024-09-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloog', '0002_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images/'),
        ),
    ]
